#!/bin/bash

function task_exec() {
	whoami
	hostname
	uptime 1>&2
}

function task_setup() {
	# Available environment variables
	# $ASSET_DIR
	# $TOOL_DIR
	# $INCLUDE_DIR

	# Available Configuration
	# $PARALLEL "true"/"false"

	INCLUDES+=()

	SSH_USER=server
	SSH_IDENTITY_FILE=$ASSET_DIR/id_rsa
	
	FILES+=()

	TASK_ISSET="yes"
}

if [ -z $HOSTMODE ]; then
	task_exec
else
	task_setup
fi
