#!/bin/bash

function task_setup() {
	SSH_USER=root
	SSH_IDENTITY_FILE=$ASSET_DIR/id_jenkins

	FILES+=("$ASSET_DIR/id_user.pub" "$ASSET_DIR/id_jenkins.pub")
	INCLUDES+=("$INCLUDE_DIR/pkgmanager")

	TASK_ISSET="yes"
}

function task_exec() {
	pkg_update
	pkg_install sudo

	groupadd sudo
	useradd -s /bin/bash -d /home/server -m -U -G sudo server

	tee /etc/sudoers.d/autosetup_sudoconf << EOF
# Configured by lTask
%sudo ALL=(ALL) NOPASSWD: ALL
EOF
	su server << EOF
cd
mkdir .ssh; cd .ssh
touch authorized_keys
EOF

	cat id_user.pub >> /home/server/.ssh/authorized_keys
	cat id_jenkins.pub >> /home/server/.ssh/authorized_keys

	echo > /etc/motd
}

if [ -z $HOSTMODE ]; then
	task_exec
else
	task_setup
fi
