#!/bin/bash

function task_exec() {

	cat id_jenkins.pub >> /home/server/.ssh/authorized_keys

}

function task_setup() {
	# Available environment variables
	# $ASSET_DIR
	# $TOOL_DIR

	SSH_USER=server
	SSH_IDENTITY_FILE=$ASSET_DIR/id_jenkins

	FILES+=("$ASSET_DIR/id_jenkins.pub")

	TASK_ISSET="yes"
}

if [ -z $HOSTMODE ]; then
	task_exec
else
	task_setup
fi
