#!/bin/bash

function task_exec() {
	ret=0
	sudo pkg_update
	ret=$(($ret + $?))

	sudo pkg_upgrade
	ret=$(($ret + $?))
	
	exit $ret
}

function task_setup() {
	# Available environment variables
	# $ASSET_DIR
	# $TOOL_DIR
	
	INCLUDES+=("$INCLUDE_DIR/pkgmanager")

	SSH_USER=server
	SSH_IDENTITY_FILE=$ASSET_DIR/id_jenkins
	
	TASK_ISSET="yes"
}

if [ -z $HOSTMODE ]; then
	task_exec
else
	task_setup
fi
