#!/bin/bash

function task_exec() {
	pkg_update
	pkg_upgrade
}

function task_setup() {
	INCLUDES+=("$INCLUDE_DIR/pkgmanager")

	SSH_USER=server
	#SSH_IDENTITY_FILE=$ASSET_DIR/id_rsa
	
	FILES+=()

	TASK_ISSET="yes"
}

if [ -z $HOSTMODE ]; then
	task_exec
else
	task_setup
fi
